# Generated by Django 4.1.7 on 2023-04-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipe_user_alter_recipe_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
